FROM python:3.11-slim

WORKDIR /app

COPY cloud-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cloud-service/app ./app
COPY cloud-service/generate_encrypted_config.py .

EXPOSE 8001

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
